---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Debian/Ubuntu configuration for Packer.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.9
  platforms:
  - name: Debian
    versions:
      - all
  - name: Ubuntu
    versions:
      - all
  - name: CentOS
    versions:
      - 7.0
  - name: openSuse
    versions:
      - 13.2
  categories:
    - cloud
    - system
    - packaging
    - development
